/* AUTOMATICALLY GENERATED VERILOG-2001 SOURCE CODE.
** GENERATED BY CLASH 1.9.0. DO NOT MODIFY.
*/
`default_nettype none
`timescale 100fs/100fs
module Blink_topEntity_probeHandlerC
    ( // Inputs
      input wire [70:0] c$arg


      // Outputs
    , output wire [70:0] c$case_alt
    );
  wire [69:0] c$app_arg;
  wire [15:0] _magic1;
  wire [3:0] _version1;
  wire  _res2;
  wire [69:0] fwdIn;
  wire  bwdIn;
  wire [68:0] a1;
  wire [3:0] _last1;
  wire  _abort1;
  wire [31:0] _data1;

  assign c$app_arg = fwdIn[69:69] ? {1'b1,{_data1,
                                           _last1,   {_magic1,   _version1,   _res2,
                                                      1'b1,   1'b1,   1'b0,   a1[8:5] & 4'b0100,
                                                      a1[4:1] & 4'b0100},
                                           _abort1}} : {1'b0,69'bxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx};

  assign c$case_alt = {bwdIn,   c$app_arg};

  assign _magic1 = a1[32:17];

  assign _version1 = a1[16:13];

  assign _res2 = a1[12:12];

  assign fwdIn = c$arg[70:1];

  assign bwdIn = c$arg[0:0];

  assign a1 = fwdIn[68:0];

  assign _last1 = a1[36:33];

  assign _abort1 = a1[0:0];

  assign _data1 = a1[68:37];


endmodule

